import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientProvider from "@/provider/client-provider";
import { PWAInstallBanner } from "@/components/PWAInstallBanner";
import Pwa from "../provider/pwa";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Templo Rocha Eterna",
  description: "Generated by Living Stones Digital",
  manifest: "/manifest.json",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClientProvider>
          <PWAInstallBanner />
          <Pwa />
          {children}
        </ClientProvider>
      </body>
    </html>
  );
}
